"""empty message

Revision ID: 8d3446a3695e
Revises: 99d1d734e064
Create Date: 2021-08-06 16:52:46.977093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3446a3695e'
down_revision = '99d1d734e064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SurfSpot', sa.Column('wave_image', sa.String(), nullable=True))
    op.alter_column('SurfSpot', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('SurfSpot', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('SurfSpot', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('SurfSpot', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('SurfSpot', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('SurfSpot', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('SurfSpot', 'wave_image')
    # ### end Alembic commands ###
