"""empty message

Revision ID: 99d1d734e064
Revises: 
Create Date: 2021-08-06 15:39:13.484446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d1d734e064'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SurfSpot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('wave_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Surfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('stance', sa.String(), nullable=False),
    sa.Column('hometown', sa.String(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SurfContest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contestName', sa.String(), nullable=False),
    sa.Column('contestDate', sa.DateTime(), nullable=False),
    sa.Column('surfSpotId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['surfSpotId'], ['SurfSpot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surfer_contests',
    sa.Column('surfer_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['SurfContest.id'], ),
    sa.ForeignKeyConstraint(['surfer_id'], ['Surfer.id'], ),
    sa.PrimaryKeyConstraint('surfer_id', 'contest_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surfer_contests')
    op.drop_table('SurfContest')
    op.drop_table('Surfer')
    op.drop_table('SurfSpot')
    # ### end Alembic commands ###
